### ISSUE TITLE
La position du formulaire d'inscription à la newsletter est déterminé

### ISSUE THREAD

**Issue by liZe** [Kozea/www-teepy#29]

**Comment by annabellou** [comment]
Vu @Lilouu pour le fonctionnement.

- le bouton d'inscription se situe dans le footer

![bouton inscription newsletter](https://user-images.githubusercontent.com/7512422/60675142-f62fbb00-9e7b-11e9-821f-a2704254517c.png)

- quand on clique dessus, on est redirigé sur une page du site qui contient les infos utiles quant à l'inscription (très fortement inspirée de [celle du site de Pharminfo.fr](https://us8.list-manage.com/subscribe?u=dde3a36d2f82cc3f75534f533&id=690485c561))

![page newsletter](https://user-images.githubusercontent.com/7512422/60675271-3f800a80-9e7c-11e9-9d84-36983623fbd6.png)

Le bouton "s'abonner" envoi un mail sur la boite mail des contacts backoffice, et le mail du prospect sera rentré à la main dans la liste des abonnés de la newsletter. On part sur ce fonctionnement pour ne pas avoir à gérer toute la partie "inscription automatique" via SendinBlue / MailChimp, qui est un peu galère.
