### ISSUE TITLE
La méthode nécessaire à la mise à jour des vidéos est déterminée

### ISSUE THREAD

**Issue by liZe** [Kozea/www-teepy#31]

**Comment by annabellou** [comment]
Après investigation, j'ai retrouvé [la trace de la vidéo](https://github.com/Kozea/teepy/issues/865) "démo / fonctionnement de l'outil".

Elle a été réalisée par capture directe par un gestionnaire tiers-payant, puis retravaillé par Hugo pour ajouter du texte afin de respecter un scénario défini ([ici](https://github.com/Kozea/teepy/issues/764) et [là ](https://github.com/Kozea/teepy/issues/766)).

Actuellement, cette vidéo [est en ligne en mode privé sur le Youtube de Kozea](https://www.youtube.com/watch?v=qzsWoAVkEm8&feature=youtu.be), ce qui veut dire que l'on ne peut pas la trouver sans avoir eu le lien. J'ai demandé à @Dodeau si elle savait à quel moment cette vidéo est partagé avec les clients, mais elle n'a pas su me répondre. Autrement dit, je ne sais pas si cette vidéo est toujours partagée avec les clients (peut-être à l'envoi d'un mail de bienvenue ou lorsqu'ils demandent de l'aide ?).

Du coup, il faudrait d'abord déterminer si cette vidéo de présentation est toujours utile avant d'en refaire une nouvelle. Si on décide d'en refaire une, @Camille-Cz se propose pour la capture vidéo, et il faudra écrire un scénario / étapes importantes à montrer et ensuite il sera nécessaire de la monter.

Ceci étant, cette vidéo est à destination des clients qui utilisent eux-même l'outil, hors cela représente une toute petite part de l'ensemble des clients (mais elle peut rester utile, quitte à la compléter / remplacer par un document papier). À terme, le site internet de la plateforme devra être revu dans son contenu, actuellement plus tourné vers la gestion en interne que l'externalisation alors que c'est cette dernière offre qui attire le plus de clients.
