### ISSUE TITLE
Les captures d'écran de l'application sont réalisées

### ISSUE THREAD

**Issue by liZe** [Kozea/www-teepy#32]

**Comment by annabellou** [comment]
Voici [le lien Drive](https://drive.google.com/open?id=1tC7AsmywdI7DE3bgSlQjUX4GtYRszswb) avec les nouvelles images, qui portent le même nom que les images actuelles.

Il y a l'image du header de la page d'accueil, et 5 images pour la page "Gestion en interne" (4 fonctionnalités et l'écran de base).
