### ISSUE TITLE
L'ajout d'une pop-up dès l'arrivée sur le site est analysé

### ISSUE THREAD

**Issue by Lilouu** [Kozea/www-teepy#35]
Face à l'actualité nous tenons à vous assurer que l'ensemble des équipes de Backoffice est mobilisé pour assurer la continuité de nos missions à votre service. Et pour vous soutenir dans cette épreuve nous souhaitons vous accompagner davantage en vous proposant de gérer votre tiers-payant sans engagement, ainsi que vos télétransmissions à des tarifs préférentiels.

Bouton d'action : **Contactez-nous pour en savoir plus**
Redirection vers le mail backoffice@lagestiondutierspayant.fr

**Comment by annabellou** [comment]
Voici ma proposition : 
![Bandeau Backoffice](https://user-images.githubusercontent.com/7512422/77157454-aa708080-6aa1-11ea-81c4-24f183fee577.png)

Après avoir fait le tour de plusieurs sites de vente en ligne, il en est ressorti que la tendance était plutôt au bandeau de texte qu’à une pop up.
Je propose donc un simple bandeau de texte, placé en bas de page, qui reste fixe même en scrollant la page. Il n’y a pas de possiblité de fermer / cacher ce bandeau. L’offre est mise en valeur ainsi que le bouton de contact.

Qu’en penses-tu @Lilouu ?

**Comment by Lilouu** [comment]
Comme les autres ok ça me va !!
