### ISSUE TITLE
Le bandeau de texte est mis en prod

### ISSUE THREAD

**Issue by Lilouu** [Kozea/www-teepy#36]
Suite #35

**Comment by gentooboontoo** [comment]
@annabellou, pourras-tu me donner ton avis sur le site de test https://test-www-teepy-specialoffer.kozea.fr/ ? (notamment le bouton d'action au survol).

@Lilouu, hormis les corrections de style éventuelles proposées par @annabellou, ça te va ?

**Comment by Lilouu** [comment]
Oui ça me va ! :+1:

**Comment by annabellou** [comment]
Ça me va aussi !

**Comment by gentooboontoo** [comment]
Merci à vous deux.

Déployé.
