### ISSUE TITLE
Les prix sont supprimés du site

### ISSUE THREAD

**Issue by Lilouu** [Kozea/www-teepy#39]
Suite https://github.com/Kozea/kozea/issues/1937

Mes propositions de texte (approuvé côté commercial) pour remplacer le bloc de prix sur la page d'accueil et dans l'onglet Contact :
Accueil : "Profitez d'un diagnostic rapide et sans engagement"
![Capture d’écran de 2020-09-29 10-34-31](https://user-images.githubusercontent.com/17597956/94535440-db482400-0241-11eb-9309-0b889d0034be.png)

Contact : "Profitez d'un diagnostic rapide et sans engagement pour la gestion de votre tiers-payant."
![Capture d’écran de 2020-09-29 10-35-47](https://user-images.githubusercontent.com/17597956/94535454-dedbab00-0241-11eb-8dfe-a99958578648.png)

(Et du coup il faut enlever l'astérisque en bas avant "Consultez-nous pour un devis personnalisé")

@annabellou à voir si tu peux regarder côté graphique les changements que ça induit et si c'est toi ou @gentooboontoo qui effectuera les changements sur le site.

**Comment by gentooboontoo** [comment]
Comme vu tous ensemble, @annabellou va regarder les modifications graphiques éventuelles puis les intégrer au site. Je prendrai le relais en cas de besoin.

**Comment by annabellou** [comment]
Voici ma proposition graphique pour rafraichir le header : 

![Teepy---header-diagnosticdesk](https://user-images.githubusercontent.com/7512422/95728334-b14c2400-0c7b-11eb-8594-12e4ed16ee88.png)

Les changements que je propose : 

- supprimer l'image de l'ordinateur en fond qui ne facilite pas la lecture et qui ne permet pas non plus d'apprécier la capture d'écran de l'outil,
- un fond gris clair pour marquer la partie du header tout en permettant une lecture facile du texte,
- le logo dans ses couleurs d'origine et non pas en blanc,
- le regroupement des 3 points de la liste en un seul paragraphe, plus proche d'une mise en forme de type landing page,
- insertion du "diagnostic rapide et sans engagement",
- bouton de téléchargement du livre blanc allégé,
- nouvelle image de l'ordinateur, plus petite et épurée.

Et voilà ce que cela pourrait donner en version mobile (à voir si on conserve l'image de l'ordinateur, cela fera peut-être trop chargé)

![Teepy---header-diagnosticmobile](https://user-images.githubusercontent.com/7512422/95728914-64b51880-0c7c-11eb-9d20-5a8aec8397b1.png)

@Lilouu, quand tu veux pour en discuter :)

**Comment by Lilouu** [comment]
@annabellou le header paraît plus moderne et plus sympa comme ça c'est vrai ! 

Pour le texte en 1 paragraphe, voici ma proposition légèrement retravaillée : "Externalisez la gestion de votre tiers-payant et suivez l'évolution du montant de vos impayés en toute autonomie avec la plateforme Backoffice, développée par [Kozea group](https://kozea.fr/)." ; validé avec Mme Berthe notamment. 

Ce texte sera temporaire de toute façon, avec le changement de nom de l'outil, et si on revoit la stratégie globale de Kozea group + l'orientation de Backoffice sur l'externalisation principalement, les textes changeront sur tout le site (et le design aussi potentiellement).

**Comment by annabellou** [comment]
On part donc sur cette mise en page : 

![Teepy---header-diagnostic](https://user-images.githubusercontent.com/7512422/95961611-8f7ea880-0e05-11eb-9a9d-88fac7d6fa21.png)

**Comment by annabellou** [comment]
C'est en ligne !
