### ISSUE TITLE
Le livre blanc est mis à jour

### ISSUE THREAD

**Issue by Lilouu** [Kozea/www-teepy#42]
Changer le livre blanc "Comment redonner de la valeur au métier de pharmacien en optimisant la gestion du tiers-payant ?" par ce document mis à jour : 
[Backoffice-LivreBlanc-MAJ.2020.pdf](https://github.com/Kozea/www-teepy/files/5687965/Backoffice-LivreBlanc-MAJ.2020.pdf)
Merci

**Comment by gentooboontoo** [comment]
@Lilouu : 

* il n'y a plus de date d'édition par rapport au précédent livre blanc (juin 2017)
* le poids du fichier est de 4 Mo au lieu de 0,5

C'est quand même OK pour toi ?

**Comment by Lilouu** [comment]
@gentooboontoo 
Oui la date c'est fait exprès et pour le poids je ne sais pas trop pourquoi, à part peut être les nouvelles images importées par @annabellou qui ont fait augmenter le poids mais sinon oui c'est ok !

**Comment by gentooboontoo** [comment]
Mis à jour. cc @annabellou pour le poids du fichier si jamais ce n'est pas normal.
