### ISSUE TITLE
La certification Qualiopi est intégrée sur le site institutionnel

### ISSUE THREAD

**Issue by annabellou** [Kozea/www-teepy#48]
Suite à https://github.com/Kozea/teepy/issues/1770.

**Comment by annabellou** [comment]
Le contenu et le style sont implémentés sur la branche `qualiopi_48` : dans l'idéal, j'aimerais pousser cette branche sur master au même moment que les éléments qui seront intégrés suite au ticket https://github.com/Kozea/teepy/issues/1806 (sauf si on préfère les séparer et les mettre en production l'un après l'autre).

**Comment by gentooboontoo** [comment]
> dans l'idéal, j'aimerais pousser cette branche sur master au même moment que les éléments qui seront intégrés suite au ticket Kozea/teepy#1806

Comme tu préfères mais normalement il n'y a pas de raison de bloquer le déploiement (sauf si le ticket issu de #1806 aura un fort impact dessus)

:+1: sinon pour le reste.

**Comment by annabellou** [comment]
Non, à priori les changements du ticket https://github.com/Kozea/teepy/issues/1806 n'auront aucun impact sur les modifications de ce ticket : c'était juste par rapport au fait qu'on pourrait "lancer une communication" en même temps sur ces 2 sujets, mais je ne pense pas que ça soit gênant d'au moins mettre en ligne la partie sur la certification Qualiopi.

Du coup, je te soumets une pull request pour un relecture du code avant déploiement ?

**Comment by gentooboontoo** [comment]
Oui, tu peux soumettre la PR, je vais regarder.

**Comment by annabellou** [comment]
C'est en ligne !
