### ISSUE TITLE
Le texte de description des avantages de la page optique est modifié

### ISSUE THREAD

**Issue by annabellou** [Kozea/www-teepy#50]
Suite à #https://github.com/Kozea/teepy/issues/1807, il faudrait mettre à jour le texte de description de la partie "prise en charge complète" sur la page optique du site de Backoffice (https://www.lagestiondutierspayant.fr/optic).

Il deviendrait donc "**Prise en charge complète** traitement des rejets et impayés, rapprochement bancaire, relance des crédits"

**Comment by gentooboontoo** [comment]
ping @annabellou (pour profiter des changements récents si ce ticket est toujours d'actualité).
